orbita_catalog_homepage:
    path: /
    defaults: { _controller: OrbitaCatalogBundle:Page:index }

orbita_catalog_category:
    path: /{id}
    defaults: { _controller: OrbitaCatalogBundle:Category:show }
    requirements:
            methods:  GET
            id: \d+

orbita_catalog_users:
    path: /users
    defaults: { _controller: OrbitaCatalogBundle:Users:index }

orbita_catalog_site_create:
    path:  /add
    defaults: { _controller: "OrbitaCatalogBundle:Site:create" }
    requirements:
        methods:  POST
