<?php

namespace Orbita\CatalogBundle\Entity\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use Doctrine\ORM\EntityRepository;

class CategoryRepository extends EntityRepository
{
    public function getCategories($limit = null)
    {
        $qb = $this->createQueryBuilder('b')
            ->select('b')
            ->addOrderBy('b.title', 'ASC');

        if (is_null($limit) === false)
            $qb->setMaxResults($limit);
        return $qb->getQuery()->getResult();
    }

    public function getCategory($catId, $limit = null)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.id = :cat_id')
            ->setParameter('cat_id', $catId);

        return $qb->getQuery()
            ->getSingleResult();
    }
}
